services:
  mongoserver:
    image: mongo
    container_name: mongodb-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - book-network

  book-backend:
    image: thisissikandar/book-backend:v1
    container_name: backend-server
    ports: -'8000:8000'
    networks:
      - book-network
    env_file:
      - .env
    depends_on:
      - mongoserver

networks:
  book-network:
    driver: bridge
